### PR TITLE
Add SMSPLUS-GX Core

### PR DESCRIPTION
**Pull request by michael-j-green**
This PR adds:
* the SMSPLUS-GX core (the build script is still pointing to the upstream repo, which will need to be updated)
  * tested working in a local build of EJS
* all builds are now under a compile sub-directory which I found a bit easier to clean up after failed builds
* adds docker devcontainer support, to build a dev environment when used with docker and VS Code

### CODE REVIEW

**Comment by ethanaobrien** [comment]
Did you make sure that it builds when threading is enabled?

Also, made a fork: https://github.com/EmulatorJS/smsplus-gx

**Comment by michael-j-green** [comment]
I'll do that testing today sometime.

And thanks for making the fork. I don't have that permission :) I'll update the build script today to use the new fork.

**Comment by michael-j-green** [comment]
I'll also update the README with a warning that builds can only take place on amd64 platforms - the compilation fails on ARM processors.

**Comment by michael-j-green** [comment]
According to this segment of the build.sh file:
```bash
    build
    if [ "$thread" != "no" ]; then
        buildThreads
    fi
    if [ "$legacy" != "no" ]; then
        buildLegacy
        if [ "$thread" != "no" ]; then
             buildThreadsLegacy
        fi
    fi
```
It'll build both threaded and non-threaded for new and legacy unless you explicitly add the string ``no`` to the end of the ``compileProject "smsplus-gx" "https://github.com/EmulatorJS/smsplus-gx" "./" "Makefile.libretro"``.

The first ``no`` you add determines if a threaded version should be built, and the second ``no`` determines if a legacy version should be built.

If _any_ other string (even zero length ones) is added in place of the ``no``, the threaded versions and legacy versions will be built:
Screenshot 2024-02-11 at 7 59 33 pm

All core versions build successfully.

**Comment by ethanaobrien** [comment]
Legacy cores are actually something different entirely, they just compile with gles2 instead of gles3, and unless you enabled gles3 when building with RetroArch you were building with gles2.

> All core versions build successfully, but the threaded version refuses to run
Is there anything in the console? Try passing `-pthread` when building the core files

**Comment by michael-j-green** [comment]
Just tested the threaded version again. I get a 404 not found. I'm guessing I've made a mistake somewhere in EJS with the name (since it works with threads disabled). Here are the files generated:
* smsplus-legacy-wasm.data
* smsplus-thread-legacy-wasm.data
* smsplus-thread-wasm.data
* smsplus-wasm.data

Any ideas where the mistake might have been made?

**Comment by ethanaobrien** [comment]
Well, what file is the network tab in devtools trying to pull that reports 404. Likely a server cache thing or a client cache thing

**Comment by michael-j-green** [comment]
You can tell it's Monday morning haha... the 404 was for socket.io.min.

The error that EJS is displaying is "Error for site owner, check console", with this in the console: [Warning] Threads is set to true, but the SharedArrayBuffer function is not exposed. Threads requires 2 headers to be set when sending you html page. See https://stackoverflow.com/a/68630724 (emulator.js, line 649)

I'm running from localhost, and need to look into my host settings for the cross-origin headers.

**Comment by ethanaobrien** [comment]
Got it

**Comment by michael-j-green** [comment]
With the headers set - threads works!

Screenshot 2024-02-12 at 11 07 08 am

**Comment by ethanaobrien** [comment]
Nice! So just re enable threads and legacy and I'll merge. Thanks!

**Comment by michael-j-green** [comment]
Done! You may merge when ready :)

**Comment by michael-j-green** [comment]
Note: this PR also updates the README.

**Review by ethanaobrien — APPROVED** [review]

**Pull request merged**
